import type { StageDefinition, Terrain, TileDefinition, UnitDefinition } from './types'

const tile = (q: number, r: number, terrain: Terrain): TileDefinition => ({ q, r, terrain })

export const UNIT_DEFINITIONS: Record<string, UnitDefinition> = {
  yao: {
    id: 'yao',
    name: '姚仁',
    title: '祖靈盾戟衛',
    role: 'halberd',
    side: 'allies',
    maxHp: 128,
    attack: 29,
    armor: 12,
    move: 2,
    range: 1,
    color: 0x246b62,
    accent: 0xf1c45b,
    sigil: '盾',
    ability: {
      name: '藤盾壁',
      description: '立起藤盾進入守勢 2 回合，受到的傷害減半。',
      kind: 'guard',
      power: 50,
      range: 0,
    },
  },
  sora: {
    id: 'sora',
    name: '林曦',
    title: '赤羽獵弓手',
    role: 'ranger',
    side: 'allies',
    maxHp: 82,
    attack: 34,
    armor: 4,
    move: 3,
    range: 3,
    color: 0xb94935,
    accent: 0xffd477,
    sigil: '弓',
    ability: {
      name: '烽火箭',
      description: '對目標及其相鄰六角格造成 26 點傷害。',
      kind: 'volley',
      power: 26,
      range: 3,
    },
  },
  mei: {
    id: 'mei',
    name: '安湄',
    title: '潮聲祭司',
    role: 'priest',
    side: 'allies',
    maxHp: 88,
    attack: 25,
    armor: 5,
    move: 2,
    range: 2,
    color: 0x356ea5,
    accent: 0xa9e0ee,
    sigil: '潮',
    ability: {
      name: '祖泉祝禱',
      description: '為 2 格內所有友軍恢復 30 點生命。',
      kind: 'heal',
      power: 30,
      range: 2,
    },
  },
  taka: {
    id: 'taka',
    name: '塔卡',
    title: '祖骨死靈師',
    role: 'necromancer',
    side: 'allies',
    maxHp: 94,
    attack: 31,
    armor: 7,
    move: 4,
    range: 1,
    color: 0x72559b,
    accent: 0xd8b8ff,
    sigil: '疾',
    ability: {
      name: '祖魂追擊',
      description: '召喚祖魂襲擊 3 格內的目標，造成高額傷害。',
      kind: 'volley',
      power: 48,
      range: 3,
    },
  },
  nai: {
    id: 'nai',
    name: '奈雅',
    title: '星潮航海法師',
    role: 'navigator',
    side: 'allies',
    maxHp: 84,
    attack: 27,
    armor: 5,
    move: 3,
    range: 2,
    color: 0x2f8d86,
    accent: 0x91e0d4,
    sigil: '航',
    ability: { name: '順潮風', description: '以潮風衝擊 3 格內目標。', kind: 'volley', power: 38, range: 3 },
  },
  kavi: {
    id: 'kavi',
    name: '卡維',
    title: '聚落築造師',
    role: 'builder',
    side: 'allies',
    maxHp: 116,
    attack: 28,
    armor: 10,
    move: 2,
    range: 1,
    color: 0xa66b2b,
    accent: 0xf2c06f,
    sigil: '築',
    ability: { name: '竹壁工事', description: '築起臨時工事，進入守勢 2 回合。', kind: 'guard', power: 50, range: 0 },
  },
  luma: {
    id: 'luma',
    name: '露瑪',
    title: '草藥祭司',
    role: 'herbalist',
    side: 'allies',
    maxHp: 86,
    attack: 22,
    armor: 6,
    move: 2,
    range: 2,
    color: 0x547c45,
    accent: 0xb9df8c,
    sigil: '藥',
    ability: { name: '林息祝禱', description: '為 2 格內所有友軍恢復 34 點生命。', kind: 'heal', power: 34, range: 2 },
  },
  panu: {
    id: 'panu',
    name: '巴努',
    title: '水鹿騎兵',
    role: 'cavalry',
    side: 'allies',
    maxHp: 102,
    attack: 33,
    armor: 7,
    move: 5,
    range: 1,
    color: 0x324f79,
    accent: 0x9ab9ef,
    sigil: '鹿',
    ability: { name: '鹿角奔襲', description: '乘水鹿突進攻擊 4 格內目標。', kind: 'lunge', power: 50, range: 4 },
  },
  sina: {
    id: 'sina',
    name: '希娜',
    title: '窯火法師',
    role: 'fire_mage',
    side: 'allies',
    maxHp: 80,
    attack: 36,
    armor: 3,
    move: 2,
    range: 3,
    color: 0xb8652b,
    accent: 0xffc36f,
    sigil: '火',
    ability: { name: '陶窯烈焰', description: '以窯火焚擊目標及其相鄰六角格。', kind: 'volley', power: 30, range: 3 },
  },
  ember_raider: {
    id: 'ember_raider',
    name: '赤赭獵手',
    title: '敵對獵團突擊者',
    role: 'raider',
    side: 'enemies',
    maxHp: 62,
    attack: 19,
    armor: 3,
    move: 3,
    range: 1,
    color: 0x7f332b,
    accent: 0xe6804d,
    sigil: '刃',
    ability: { name: '撕裂', description: '兇猛的近身斬擊。', kind: 'lunge', power: 28, range: 1 },
  },
  salt_archer: {
    id: 'salt_archer',
    name: '沼岸投矛手',
    title: '蘆葦灘遠投者',
    role: 'artillery',
    side: 'enemies',
    maxHp: 52,
    attack: 21,
    armor: 2,
    move: 2,
    range: 3,
    color: 0x6e4b37,
    accent: 0xe8c298,
    sigil: '矢',
    ability: { name: '壓制箭', description: '遠距離射擊。', kind: 'volley', power: 22, range: 3 },
  },
  mire_guard: {
    id: 'mire_guard',
    name: '藤甲守衛',
    title: '巨藤盾壁',
    role: 'vanguard',
    side: 'enemies',
    maxHp: 90,
    attack: 17,
    armor: 8,
    move: 2,
    range: 1,
    color: 0x425b4c,
    accent: 0x93b58b,
    sigil: '甲',
    ability: { name: '固守', description: '依靠重甲穩住陣線。', kind: 'guard', power: 40, range: 0 },
  },
  cannoner: {
    id: 'cannoner',
    name: '河石投手',
    title: '黑潮投石兵',
    role: 'artillery',
    side: 'enemies',
    maxHp: 58,
    attack: 25,
    armor: 3,
    move: 1,
    range: 3,
    color: 0x4d4542,
    accent: 0xf0a552,
    sigil: '砲',
    ability: { name: '石雨', description: '緩慢但沉重的遠距投石。', kind: 'volley', power: 26, range: 3 },
  },
  commander: {
    id: 'commander',
    name: '烏魯首領',
    title: '黑潮獵團領袖',
    role: 'commander',
    side: 'enemies',
    maxHp: 145,
    attack: 28,
    armor: 10,
    move: 2,
    range: 2,
    color: 0x512c35,
    accent: 0xffbd59,
    sigil: '王',
    ability: { name: '獸牙號令', description: '指揮獵團穩住戰線。', kind: 'guard', power: 40, range: 0 },
  },
}

export const HERO_IDS = ['yao', 'sora', 'mei', 'taka', 'nai', 'kavi', 'luma', 'panu', 'sina']

const ALLY_DEPLOYMENT: Record<string, { q: number; r: number }> = {
  sora: { q: 0, r: 2 },
  taka: { q: 0, r: 4 },
  nai: { q: 0, r: 0 },
  sina: { q: 0, r: 6 },
  yao: { q: 1, r: 2 },
  mei: { q: 1, r: 4 },
  luma: { q: 1, r: 6 },
  kavi: { q: 2, r: 1 },
  panu: { q: 2, r: 3 },
}

const BASE_TERRAIN: TileDefinition[] = [
  tile(2, 1, 'forest'), tile(3, 1, 'forest'), tile(3, 5, 'forest'), tile(5, 4, 'forest'),
  tile(4, 2, 'hill'), tile(6, 2, 'hill'), tile(6, 4, 'hill'),
  tile(3, 3, 'marsh'), tile(5, 1, 'marsh'), tile(5, 5, 'marsh'),
  tile(4, 0, 'water'), tile(5, 0, 'water'), tile(6, 0, 'water'),
  tile(4, 6, 'water'), tile(5, 6, 'water'), tile(6, 6, 'water'),
]

const SITE_STORIES = [
  {
    id: 'fengbitou-landing', chapter: 'I', archaeologyLabel: '鳳鼻頭遺址', name: '鳳鼻頭登岸',
    subtitle: '約七千年前，三人踏上陌生海岸',
    briefing: '姚仁、林曦與安湄乘獨木舟抵達潟湖與丘陵交界。先清出安全營地，讓第一簇祖火在島上燃起。',
    victoryText: '三人在海風中立起藤架，保存種子、火種與淡水。這裡成為祖先在南方海岸的第一個落腳點。',
    defeatText: '潮水與敵對獵團迫使三人退回沙洲。他們保住火種，等待下一次靠岸。',
    objective: 'eliminate' as const, objectiveLabel: '清除營地周邊威脅', roundLimit: 14, swiftRound: 9,
    mapPosition: { x: 0.42, y: 0.61 }, partySize: 3,
  },
  {
    id: 'bajia-riverbank', chapter: 'II', archaeologyLabel: '歸仁八甲遺址', name: '八甲河階',
    subtitle: '沿河尋找能長久耕作的高地',
    briefing: '三人逆流進入河階，泥灘間藏著肥沃土地。守住取水點兩回合，確認洪水退去後能建立季節營地。',
    victoryText: '河階上的火塘沒有熄滅，粗繩紋陶罐盛滿新水。第一條從海岸通往內陸的路被記住了。',
    defeatText: '暴漲的溪流沖散工事，三人撤回高地，準備在下一個乾季再來。',
    objective: 'hold' as const, objectiveLabel: '占領取水點並守住 2 回合', roundLimit: 14, swiftRound: 10,
    mapPosition: { x: 0.51, y: 0.34 }, partySize: 3,
  },
  {
    id: 'nanguanli-east', chapter: 'III', archaeologyLabel: '南關里東遺址', name: '南關里東火種',
    subtitle: '祖魂回應，第四位同行者現身',
    briefing: '黑潮獵團包圍了濕地聚落。祖骨死靈師塔卡願意同行，但必須先擊退獵團首領。',
    victoryText: '塔卡以祖骨杖安撫亡者，加入隊伍。四人把新的火種帶進台南平原的潟湖邊。',
    defeatText: '祖魂警告眾人時機未到。四人退入蘆葦深處，等待黑潮獵團露出破綻。',
    objective: 'commander' as const, objectiveLabel: '擊敗黑潮獵團首領', roundLimit: 13, swiftRound: 9,
    mapPosition: { x: 0.43, y: 0.14 }, partySize: 4,
  },
  {
    id: 'nanguanli-lagoon', chapter: 'IV', archaeologyLabel: '南關里遺址', name: '南關里潮田',
    subtitle: '在鹹淡水交界試種第一片田',
    briefing: '潟湖水位反覆變化，幼苗與火塘都需要守護。占住高地，撐過敵對獵團的試探。',
    victoryText: '四人學會辨認潮汐與土色，第一片小米田在潟湖旁站穩。',
    defeatText: '鹽水漫過幼苗，眾人收回種子。失去一季，卻換來辨認潮田的知識。',
    objective: 'hold' as const, objectiveLabel: '占領潮田高地並守住 2 回合', roundLimit: 14, swiftRound: 10,
    mapPosition: { x: 0.50, y: 0.21 }, partySize: 4,
  },
  {
    id: 'wangliao-forest', chapter: 'V', archaeologyLabel: '網寮遺址', name: '網寮林徑',
    subtitle: '星潮航海法師加入五人行列',
    briefing: '奈雅從海霧中帶來星象與季風知識。護送她穿越林徑，清除通往北方水道的阻礙。',
    victoryText: '奈雅在貝殼上刻下潮向，五人的路不再只靠記憶。海與河第一次連成一張心中的地圖。',
    defeatText: '濃霧遮住星位，隊伍退回林緣。奈雅仍留下，等待天空重新放晴。',
    objective: 'eliminate' as const, objectiveLabel: '打通林間水道', roundLimit: 14, swiftRound: 10,
    mapPosition: { x: 0.42, y: 0.28 }, partySize: 5,
  },
  {
    id: 'niuchouzi-settlement', chapter: 'VI', archaeologyLabel: '牛稠子遺址', name: '牛稠子新聚',
    subtitle: '工匠卡維為六人築起長屋',
    briefing: '卡維找到適合竹木結構的台地。保護工地、守住中央柱，讓散居營火成為真正聚落。',
    victoryText: '第一座長屋落成，六人終於有能抵禦季風與驟雨的共同屋頂。',
    defeatText: '柱穴在雨中崩塌，卡維收起石錛。工法已經記住，長屋還能重建。',
    objective: 'hold' as const, objectiveLabel: '守住長屋中央柱 2 回合', roundLimit: 14, swiftRound: 10,
    mapPosition: { x: 0.50, y: 0.36 }, partySize: 6,
  },
  {
    id: 'dagangshan-quarry', chapter: 'VII', archaeologyLabel: '大崗山遺址', name: '大崗山石場',
    subtitle: '草藥祭司露瑪帶來山林知識',
    briefing: '山腳的石材能磨製更耐用的斧鋤，卻也引來黑潮獵團。露瑪願以草藥支援奪回石場。',
    victoryText: '七人取得石材與藥草，磨製工具讓開墾不再只是與巨木硬拚。',
    defeatText: '石場暫時失守，露瑪帶眾人從密林撤離，傷者都平安回到營地。',
    objective: 'commander' as const, objectiveLabel: '擊退占據石場的首領', roundLimit: 13, swiftRound: 9,
    mapPosition: { x: 0.47, y: 0.43 }, partySize: 7,
  },
  {
    id: 'taoziyuan-alliance', chapter: 'VIII', archaeologyLabel: '桃子園遺址', name: '桃子園盟誓',
    subtitle: '鹿騎兵巴努帶來南方消息',
    briefing: '巴努騎著馴養水鹿穿過珊瑚丘陵，警告黑潮獵團正在集結。八人必須先守住盟誓火塘。',
    victoryText: '水鹿的蹄印繞過火塘，八人完成盟誓。聚落之間開始互通獵場、種子與警訊。',
    defeatText: '盟誓被迫中斷，但巴努已找到眾人。鹿徑會帶他們再次會合。',
    objective: 'hold' as const, objectiveLabel: '守住盟誓火塘 2 回合', roundLimit: 14, swiftRound: 10,
    mapPosition: { x: 0.38, y: 0.49 }, partySize: 8,
  },
  {
    id: 'fudingjin-hunt', chapter: 'IX', archaeologyLabel: '覆頂金遺址', name: '覆頂金圍獵',
    subtitle: '窯火法師希娜讓九人齊聚',
    briefing: '希娜掌握穩定燒陶與護火之術。九人聯手穿越丘陵，瓦解黑潮獵團的包圍。',
    victoryText: '九人圍坐在新陶窯旁，食物與種子得以長久保存。小隊終於成為完整的拓荒共同體。',
    defeatText: '窯火被雨水澆熄，希娜保存了乾燥火絨。九人都在，火就能再點起。',
    objective: 'eliminate' as const, objectiveLabel: '解除丘陵圍獵', roundLimit: 14, swiftRound: 10,
    mapPosition: { x: 0.45, y: 0.54 }, partySize: 9,
  },
  {
    id: 'eluanbi-starfire', chapter: 'X', archaeologyLabel: '鵝鑾鼻第二史前遺址', name: '鵝鑾鼻星火',
    subtitle: '九人走到南方盡頭，點亮新的航路',
    briefing: '烏魯首領封鎖半島尖端。九人必須在風暴前擊敗他，讓祖火成為後來者辨認海岸的星光。',
    victoryText: '星火在半島高地燃起。從台南潟湖到屏東南端，十處據點連成祖先開墾南方的第一條生命線。',
    defeatText: '風暴迫使九人離開尖端，但十處據點仍彼此呼應。南方的故事不會在此終止。',
    objective: 'commander' as const, objectiveLabel: '在風暴前擊敗烏魯首領', roundLimit: 12, swiftRound: 9,
    mapPosition: { x: 0.56, y: 0.87 }, partySize: 9,
  },
]

function alliesFor(partySize: number): StageDefinition['allies'] {
  return HERO_IDS.slice(0, partySize).map((unitId) => ({ unitId, ...ALLY_DEPLOYMENT[unitId] }))
}

function terrainFor(stageId: string, objective: StageDefinition['objective']): TileDefinition[] {
  if (stageId === 'nanguanli-lagoon') {
    return [...BASE_TERRAIN, tile(4, 3, 'hill'), tile(5, 3, 'hill')]
  }
  if (objective === 'hold') return [...BASE_TERRAIN, tile(4, 3, 'village')]
  return BASE_TERRAIN
}

function enemiesFor(index: number, objective: StageDefinition['objective']): StageDefinition['enemies'] {
  if (index === 0) {
    return [
      { unitId: 'ember_raider', q: 5, r: 1 }, { unitId: 'ember_raider', q: 6, r: 3 },
      { unitId: 'salt_archer', q: 5, r: 4 }, { unitId: 'mire_guard', q: 4, r: 2 },
    ]
  }
  const enemies: StageDefinition['enemies'] = [
    { unitId: 'ember_raider', q: 7, r: 1 }, { unitId: 'ember_raider', q: 8, r: 3 },
    { unitId: 'salt_archer', q: 7, r: 5 }, { unitId: 'mire_guard', q: 6, r: 2 },
  ]
  if (index >= 4) enemies.push({ unitId: 'cannoner', q: 8, r: 1 })
  if (index >= 6) enemies.push({ unitId: 'mire_guard', q: 6, r: 4 })
  if (objective === 'commander') enemies.push({ unitId: 'commander', q: 7, r: 3 })
  return enemies
}

export const STAGES: StageDefinition[] = SITE_STORIES.map((story, index) => ({
  ...story,
  objectiveHex: story.objective === 'hold' ? { q: 4, r: 3 } : undefined,
  objectiveTurns: story.objective === 'hold' ? 2 : undefined,
  width: 9,
  height: 7,
  allies: alliesFor(story.partySize),
  enemies: enemiesFor(index, story.objective),
  terrain: terrainFor(story.id, story.objective),
  storyImage: `assets/story/neolithic/${story.id}.png`,
}))

export function unitDefinition(id: string): UnitDefinition {
  const definition = UNIT_DEFINITIONS[id]
  if (!definition) throw new Error(`Unknown unit: ${id}`)
  return definition
}
