import type { StageDefinition, Terrain, TileDefinition, UnitDefinition } from './types'

const tile = (q: number, r: number, terrain: Terrain): TileDefinition => ({ q, r, terrain })

export const UNIT_DEFINITIONS: Record<string, UnitDefinition> = {
  yao: {
    id: 'yao',
    name: 'Yao Ren',
    title: 'Harbor Warden',
    role: 'vanguard',
    side: 'allies',
    maxHp: 128,
    attack: 29,
    armor: 12,
    move: 2,
    range: 1,
    color: 0x246b62,
    accent: 0xf1c45b,
    sigil: '盾',
    ability: {
      name: 'Breakwater',
      description: 'Brace for two turns, cutting incoming damage in half.',
      kind: 'guard',
      power: 50,
      range: 0,
    },
  },
  sora: {
    id: 'sora',
    name: 'Sora Lin',
    title: 'Sunshot Courier',
    role: 'ranger',
    side: 'allies',
    maxHp: 82,
    attack: 34,
    armor: 4,
    move: 3,
    range: 3,
    color: 0xb94935,
    accent: 0xffd477,
    sigil: '弓',
    ability: {
      name: 'Signal Flare',
      description: 'Strike a target and every adjacent hex for 26 damage.',
      kind: 'volley',
      power: 26,
      range: 3,
    },
  },
  mei: {
    id: 'mei',
    name: 'Mei An',
    title: 'Tidebinder',
    role: 'mystic',
    side: 'allies',
    maxHp: 88,
    attack: 25,
    armor: 5,
    move: 2,
    range: 2,
    color: 0x356ea5,
    accent: 0xa9e0ee,
    sigil: '潮',
    ability: {
      name: 'Returning Current',
      description: 'Restore 30 health to all nearby allies.',
      kind: 'heal',
      power: 30,
      range: 2,
    },
  },
  taka: {
    id: 'taka',
    name: 'Taka Vey',
    title: 'Ridge Strider',
    role: 'skirmisher',
    side: 'allies',
    maxHp: 94,
    attack: 31,
    armor: 7,
    move: 4,
    range: 1,
    color: 0x72559b,
    accent: 0xd8b8ff,
    sigil: '疾',
    ability: {
      name: 'Gale Lunge',
      description: 'Dash into a target up to three hexes away for heavy damage.',
      kind: 'lunge',
      power: 48,
      range: 3,
    },
  },
  ember_raider: {
    id: 'ember_raider',
    name: 'Ember Raider',
    title: 'Ash Fleet Reaver',
    role: 'raider',
    side: 'enemies',
    maxHp: 72,
    attack: 23,
    armor: 4,
    move: 3,
    range: 1,
    color: 0x7f332b,
    accent: 0xe6804d,
    sigil: '刃',
    ability: { name: 'Rend', description: 'A brutal close strike.', kind: 'lunge', power: 28, range: 1 },
  },
  salt_archer: {
    id: 'salt_archer',
    name: 'Salt Archer',
    title: 'Shoal Marksman',
    role: 'artillery',
    side: 'enemies',
    maxHp: 60,
    attack: 25,
    armor: 2,
    move: 2,
    range: 3,
    color: 0x6e4b37,
    accent: 0xe8c298,
    sigil: '矢',
    ability: { name: 'Pinning Shot', description: 'A long-range attack.', kind: 'volley', power: 22, range: 3 },
  },
  mire_guard: {
    id: 'mire_guard',
    name: 'Mire Guard',
    title: 'Drowned Bulwark',
    role: 'vanguard',
    side: 'enemies',
    maxHp: 105,
    attack: 20,
    armor: 10,
    move: 2,
    range: 1,
    color: 0x425b4c,
    accent: 0x93b58b,
    sigil: '甲',
    ability: { name: 'Hold Fast', description: 'Heavy armor and stubborn footing.', kind: 'guard', power: 40, range: 0 },
  },
  cannoner: {
    id: 'cannoner',
    name: 'Ash Cannoner',
    title: 'Furnace Gunner',
    role: 'artillery',
    side: 'enemies',
    maxHp: 66,
    attack: 30,
    armor: 3,
    move: 1,
    range: 3,
    color: 0x4d4542,
    accent: 0xf0a552,
    sigil: '砲',
    ability: { name: 'Bombard', description: 'Slow but punishing ranged fire.', kind: 'volley', power: 26, range: 3 },
  },
  commander: {
    id: 'commander',
    name: 'Marshal Voss',
    title: 'Lord of the Ash Fleet',
    role: 'commander',
    side: 'enemies',
    maxHp: 168,
    attack: 34,
    armor: 12,
    move: 2,
    range: 2,
    color: 0x512c35,
    accent: 0xffbd59,
    sigil: '王',
    ability: { name: 'Black Standard', description: 'Commands the Ash Fleet line.', kind: 'guard', power: 40, range: 0 },
  },
}

export const HERO_IDS = ['yao', 'sora', 'mei', 'taka']

export const STAGES: StageDefinition[] = [
  {
    id: 'cinder-gate',
    chapter: 'I',
    name: 'Cinder Gate',
    subtitle: 'First light over the western harbor',
    briefing: 'Ash Fleet outriders have seized the old customs road. Break their line before their signal fire reaches the bay.',
    objective: 'eliminate',
    objectiveLabel: 'Defeat every enemy regiment',
    roundLimit: 12,
    swiftRound: 7,
    width: 7,
    height: 6,
    allies: [
      { unitId: 'yao', q: 0, r: 2 },
      { unitId: 'sora', q: 0, r: 4 },
      { unitId: 'mei', q: 1, r: 3 },
    ],
    enemies: [
      { unitId: 'ember_raider', q: 5, r: 1 },
      { unitId: 'ember_raider', q: 6, r: 3 },
      { unitId: 'salt_archer', q: 5, r: 4 },
      { unitId: 'mire_guard', q: 4, r: 2 },
    ],
    terrain: [
      tile(2, 1, 'forest'), tile(2, 2, 'forest'), tile(3, 4, 'forest'),
      tile(3, 1, 'hill'), tile(5, 4, 'hill'), tile(3, 2, 'marsh'),
      tile(4, 3, 'marsh'), tile(1, 4, 'village'), tile(5, 0, 'water'),
      tile(6, 0, 'water'), tile(6, 1, 'water'),
    ],
    mapPosition: { x: 0.2, y: 0.7 },
  },
  {
    id: 'saltwind-crossing',
    chapter: 'II',
    name: 'Saltwind Crossing',
    subtitle: 'Hold the beacon against the rising tide',
    briefing: 'The sea road is flooded. Reach the bronze beacon and hold it for two full rounds while raiders close from both banks.',
    objective: 'hold',
    objectiveLabel: 'Hold the beacon for 2 rounds',
    objectiveHex: { q: 4, r: 2 },
    objectiveTurns: 2,
    roundLimit: 12,
    swiftRound: 8,
    width: 8,
    height: 6,
    allies: [
      { unitId: 'yao', q: 0, r: 2 },
      { unitId: 'sora', q: 0, r: 4 },
      { unitId: 'mei', q: 1, r: 3 },
      { unitId: 'taka', q: 1, r: 1 },
    ],
    enemies: [
      { unitId: 'ember_raider', q: 6, r: 0 },
      { unitId: 'ember_raider', q: 7, r: 3 },
      { unitId: 'salt_archer', q: 6, r: 5 },
      { unitId: 'mire_guard', q: 5, r: 2 },
      { unitId: 'cannoner', q: 7, r: 1 },
    ],
    terrain: [
      tile(2, 0, 'water'), tile(3, 0, 'water'), tile(4, 0, 'water'), tile(5, 0, 'water'),
      tile(2, 5, 'water'), tile(3, 5, 'water'), tile(4, 5, 'water'), tile(5, 5, 'water'),
      tile(2, 2, 'marsh'), tile(3, 3, 'marsh'), tile(5, 1, 'marsh'),
      tile(4, 2, 'village'), tile(3, 1, 'hill'), tile(5, 4, 'hill'),
      tile(2, 4, 'forest'), tile(6, 3, 'forest'),
    ],
    mapPosition: { x: 0.48, y: 0.5 },
  },
  {
    id: 'broken-lighthouse',
    chapter: 'III',
    name: 'The Broken Lighthouse',
    subtitle: 'Cut the head from the Ash Fleet',
    briefing: 'Marshal Voss directs the invasion from a shattered sea tower. Defeat him before the tenth bell, or the harbor will burn.',
    objective: 'commander',
    objectiveLabel: 'Defeat Marshal Voss before round 10',
    roundLimit: 10,
    swiftRound: 7,
    width: 8,
    height: 7,
    allies: [
      { unitId: 'yao', q: 0, r: 2 },
      { unitId: 'sora', q: 0, r: 5 },
      { unitId: 'mei', q: 1, r: 4 },
      { unitId: 'taka', q: 1, r: 1 },
    ],
    enemies: [
      { unitId: 'commander', q: 6, r: 3 },
      { unitId: 'mire_guard', q: 5, r: 2 },
      { unitId: 'mire_guard', q: 5, r: 4 },
      { unitId: 'cannoner', q: 7, r: 1 },
      { unitId: 'cannoner', q: 7, r: 5 },
      { unitId: 'ember_raider', q: 4, r: 3 },
    ],
    terrain: [
      tile(3, 0, 'water'), tile(4, 0, 'water'), tile(5, 0, 'water'),
      tile(3, 6, 'water'), tile(4, 6, 'water'), tile(5, 6, 'water'),
      tile(6, 3, 'hill'), tile(6, 2, 'hill'), tile(6, 4, 'hill'),
      tile(3, 2, 'forest'), tile(3, 4, 'forest'), tile(4, 1, 'marsh'),
      tile(4, 5, 'marsh'), tile(2, 3, 'village'),
    ],
    mapPosition: { x: 0.75, y: 0.3 },
  },
]

export function unitDefinition(id: string): UnitDefinition {
  const definition = UNIT_DEFINITIONS[id]
  if (!definition) throw new Error(`Unknown unit: ${id}`)
  return definition
}
