import type { StageDefinition, Terrain, TileDefinition, UnitDefinition } from './types'

const tile = (q: number, r: number, terrain: Terrain): TileDefinition => ({ q, r, terrain })

export const UNIT_DEFINITIONS: Record<string, UnitDefinition> = {
  yao: {
    id: 'yao',
    name: '姚仁',
    title: '港灣守衛',
    role: 'vanguard',
    side: 'allies',
    maxHp: 128,
    attack: 29,
    armor: 12,
    move: 2,
    range: 1,
    color: 0x246b62,
    accent: 0xf1c45b,
    sigil: '盾',
    ability: {
      name: '防波壁',
      description: '進入守勢 2 回合，受到的傷害減半。',
      kind: 'guard',
      power: 50,
      range: 0,
    },
  },
  sora: {
    id: 'sora',
    name: '林曦',
    title: '曜弓信使',
    role: 'ranger',
    side: 'allies',
    maxHp: 82,
    attack: 34,
    armor: 4,
    move: 3,
    range: 3,
    color: 0xb94935,
    accent: 0xffd477,
    sigil: '弓',
    ability: {
      name: '烽火箭',
      description: '對目標及其相鄰六角格造成 26 點傷害。',
      kind: 'volley',
      power: 26,
      range: 3,
    },
  },
  mei: {
    id: 'mei',
    name: '安湄',
    title: '潮縛師',
    role: 'mystic',
    side: 'allies',
    maxHp: 88,
    attack: 25,
    armor: 5,
    move: 2,
    range: 2,
    color: 0x356ea5,
    accent: 0xa9e0ee,
    sigil: '潮',
    ability: {
      name: '回流',
      description: '為 2 格內所有友軍恢復 30 點生命。',
      kind: 'heal',
      power: 30,
      range: 2,
    },
  },
  taka: {
    id: 'taka',
    name: '塔卡',
    title: '嶺行者',
    role: 'skirmisher',
    side: 'allies',
    maxHp: 94,
    attack: 31,
    armor: 7,
    move: 4,
    range: 1,
    color: 0x72559b,
    accent: 0xd8b8ff,
    sigil: '疾',
    ability: {
      name: '風突',
      description: '突進攻擊 3 格內的目標，造成高額傷害。',
      kind: 'lunge',
      power: 48,
      range: 3,
    },
  },
  ember_raider: {
    id: 'ember_raider',
    name: '燼火掠兵',
    title: '灰燼艦隊劫掠者',
    role: 'raider',
    side: 'enemies',
    maxHp: 72,
    attack: 23,
    armor: 4,
    move: 3,
    range: 1,
    color: 0x7f332b,
    accent: 0xe6804d,
    sigil: '刃',
    ability: { name: '撕裂', description: '兇猛的近身斬擊。', kind: 'lunge', power: 28, range: 1 },
  },
  salt_archer: {
    id: 'salt_archer',
    name: '鹽灘弓手',
    title: '淺灘射手',
    role: 'artillery',
    side: 'enemies',
    maxHp: 60,
    attack: 25,
    armor: 2,
    move: 2,
    range: 3,
    color: 0x6e4b37,
    accent: 0xe8c298,
    sigil: '矢',
    ability: { name: '壓制箭', description: '遠距離射擊。', kind: 'volley', power: 22, range: 3 },
  },
  mire_guard: {
    id: 'mire_guard',
    name: '泥沼衛士',
    title: '沉水壁壘',
    role: 'vanguard',
    side: 'enemies',
    maxHp: 105,
    attack: 20,
    armor: 10,
    move: 2,
    range: 1,
    color: 0x425b4c,
    accent: 0x93b58b,
    sigil: '甲',
    ability: { name: '固守', description: '依靠重甲穩住陣線。', kind: 'guard', power: 40, range: 0 },
  },
  cannoner: {
    id: 'cannoner',
    name: '灰燼砲手',
    title: '爐火砲兵',
    role: 'artillery',
    side: 'enemies',
    maxHp: 66,
    attack: 30,
    armor: 3,
    move: 1,
    range: 3,
    color: 0x4d4542,
    accent: 0xf0a552,
    sigil: '砲',
    ability: { name: '轟擊', description: '緩慢但致命的遠距砲火。', kind: 'volley', power: 26, range: 3 },
  },
  commander: {
    id: 'commander',
    name: '沃斯元帥',
    title: '灰燼艦隊領主',
    role: 'commander',
    side: 'enemies',
    maxHp: 168,
    attack: 34,
    armor: 12,
    move: 2,
    range: 2,
    color: 0x512c35,
    accent: 0xffbd59,
    sigil: '王',
    ability: { name: '黑旗號令', description: '指揮灰燼艦隊穩住戰線。', kind: 'guard', power: 40, range: 0 },
  },
}

export const HERO_IDS = ['yao', 'sora', 'mei', 'taka']

export const STAGES: StageDefinition[] = [
  {
    id: 'cinder-gate',
    chapter: 'I',
    name: '熔火關隘',
    subtitle: '西港晨光下的第一戰',
    briefing: '灰燼艦隊的先鋒占領了舊海關道路。突破敵陣，別讓烽火傳到港灣。',
    objective: 'eliminate',
    objectiveLabel: '擊敗所有敵軍',
    roundLimit: 12,
    swiftRound: 7,
    width: 7,
    height: 6,
    allies: [
      { unitId: 'yao', q: 0, r: 2 },
      { unitId: 'sora', q: 0, r: 4 },
      { unitId: 'mei', q: 1, r: 3 },
    ],
    enemies: [
      { unitId: 'ember_raider', q: 5, r: 1 },
      { unitId: 'ember_raider', q: 6, r: 3 },
      { unitId: 'salt_archer', q: 5, r: 4 },
      { unitId: 'mire_guard', q: 4, r: 2 },
    ],
    terrain: [
      tile(2, 1, 'forest'), tile(2, 2, 'forest'), tile(3, 4, 'forest'),
      tile(3, 1, 'hill'), tile(5, 4, 'hill'), tile(3, 2, 'marsh'),
      tile(4, 3, 'marsh'), tile(1, 4, 'village'), tile(5, 0, 'water'),
      tile(6, 0, 'water'), tile(6, 1, 'water'),
    ],
    mapPosition: { x: 0.2, y: 0.7 },
  },
  {
    id: 'saltwind-crossing',
    chapter: 'II',
    name: '鹽風渡口',
    subtitle: '在漲潮前守住烽火台',
    briefing: '海路已遭潮水淹沒。抵達青銅烽火台，面對兩岸夾擊並完整守住 2 回合。',
    objective: 'hold',
    objectiveLabel: '占領烽火台並守住 2 回合',
    objectiveHex: { q: 4, r: 2 },
    objectiveTurns: 2,
    roundLimit: 12,
    swiftRound: 8,
    width: 8,
    height: 6,
    allies: [
      { unitId: 'yao', q: 0, r: 2 },
      { unitId: 'sora', q: 0, r: 4 },
      { unitId: 'mei', q: 1, r: 3 },
      { unitId: 'taka', q: 1, r: 1 },
    ],
    enemies: [
      { unitId: 'ember_raider', q: 6, r: 0 },
      { unitId: 'ember_raider', q: 7, r: 3 },
      { unitId: 'salt_archer', q: 6, r: 5 },
      { unitId: 'mire_guard', q: 5, r: 2 },
      { unitId: 'cannoner', q: 7, r: 1 },
    ],
    terrain: [
      tile(2, 0, 'water'), tile(3, 0, 'water'), tile(4, 0, 'water'), tile(5, 0, 'water'),
      tile(2, 5, 'water'), tile(3, 5, 'water'), tile(4, 5, 'water'), tile(5, 5, 'water'),
      tile(2, 2, 'marsh'), tile(3, 3, 'marsh'), tile(5, 1, 'marsh'),
      tile(4, 2, 'village'), tile(3, 1, 'hill'), tile(5, 4, 'hill'),
      tile(2, 4, 'forest'), tile(6, 3, 'forest'),
    ],
    mapPosition: { x: 0.48, y: 0.5 },
  },
  {
    id: 'broken-lighthouse',
    chapter: 'III',
    name: '斷塔決戰',
    subtitle: '斬斷灰燼艦隊的指揮',
    briefing: '沃斯元帥在破碎燈塔指揮入侵。必須在第 10 回合前擊敗他，否則港灣將陷入火海。',
    objective: 'commander',
    objectiveLabel: '在第 10 回合前擊敗沃斯元帥',
    roundLimit: 10,
    swiftRound: 7,
    width: 8,
    height: 7,
    allies: [
      { unitId: 'yao', q: 0, r: 2 },
      { unitId: 'sora', q: 0, r: 5 },
      { unitId: 'mei', q: 1, r: 4 },
      { unitId: 'taka', q: 1, r: 1 },
    ],
    enemies: [
      { unitId: 'commander', q: 6, r: 3 },
      { unitId: 'mire_guard', q: 5, r: 2 },
      { unitId: 'mire_guard', q: 5, r: 4 },
      { unitId: 'cannoner', q: 7, r: 1 },
      { unitId: 'cannoner', q: 7, r: 5 },
      { unitId: 'ember_raider', q: 4, r: 3 },
    ],
    terrain: [
      tile(3, 0, 'water'), tile(4, 0, 'water'), tile(5, 0, 'water'),
      tile(3, 6, 'water'), tile(4, 6, 'water'), tile(5, 6, 'water'),
      tile(6, 3, 'hill'), tile(6, 2, 'hill'), tile(6, 4, 'hill'),
      tile(3, 2, 'forest'), tile(3, 4, 'forest'), tile(4, 1, 'marsh'),
      tile(4, 5, 'marsh'), tile(2, 3, 'village'),
    ],
    mapPosition: { x: 0.75, y: 0.3 },
  },
]

export function unitDefinition(id: string): UnitDefinition {
  const definition = UNIT_DEFINITIONS[id]
  if (!definition) throw new Error(`Unknown unit: ${id}`)
  return definition
}
